services:
  db:
    image: postgres:16
    container_name: dsd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dsd_user
      POSTGRES_PASSWORD: dsd_pass
      POSTGRES_DB: dsd_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
